# Generated by Django 3.1.6 on 2021-03-03 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet_vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet_vote', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Chair_vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chair_vote', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('ministry', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='legs/pdfs/')),
                ('cabinet_vote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_cab.cabinet_vote')),
                ('chair_vote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_cab.chair_vote')),
            ],
        ),
    ]
